### ISSUE TITLE
Fix broken links in API documentation

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#10]
The sphinx API documentation in `doc/api/source` currently generates broken HTML links. That is because I've moved most of the rst files into a subfolder (`api`).

It looks like that all broken links are generated through `rst_epilog` in `conf.py`, so the change should happen there.

You can use wget to find all 404s (e.g. `wget -mkEpnv http://127.0.0.1:8000/static/api/doc/index.html`)

**Comment by mbag** [comment]
There is one more issue with documentation that I have noticed, if you grep through API docstrings you will notice that there are 3 possible ways how |dc-yes/no| are described:
```
api/dc/network/views.py:18:            * |dc-yes|
api/dns/domain/views.py:47:            * |dc-yes| - ``dc_bound=true``
api/dns/record/views.py:98:            * |dc-yes| - ``domain.dc_bound=true``
```

Is there some reason why some have additional `dc_bound-true`, if not then we need to make sure that we are consistent with our documentation and decide on single way to document these attributes.

**Comment by dn0** [comment]
@mbag the later dc-yes means, that the API call is DC-bound if the dc_bound attribute on the object is set to true, otherwise it is DC-unbound.

**Comment by mbag** [comment]
@dn0 ok, so we don't need to change anything.
I have been making some changes to `doc/api/source/conf.py` `rst_epilog` so that correct paths are substituted during documentation build, however, there is one pattern that we will need to add to distinguish different levels of nesting.  
Pattern `|es example|` is used in the files that are on the same level as `es.html` i.e. `api/static/api/doc/api.html`, but same pattern can be found in files that are one level deeper `api/static/api/doc/api/`.  
For this reason I propose we add following pattern to `rst_epilog` in the `conf.py`:  
` .. |es example top| replace:: `es example <es.html>`__`  
Then we will use this pattern in RST files that are on the same level as es.rst document. This should fix the problem of relative file paths

**Comment by dn0** [comment]
👍

**Comment by mbag** [comment]
@dn0  I've created PR #11 for this issue. Please review it and comment.  
I've run your `wget` command and here is the status on my local machine:
```
http://127.0.0.1:8000/robots.txt:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/erigones.css.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/pygments.css.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/jquery.js.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/underscore.js.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/doctools.js.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/doc/_static/theme_extras.js.html:
2016-11-30 12:08:34 ERROR 404: NOT FOUND.
No data received.
http://127.0.0.1:8000/static/api/doc/_static/searchtools.js.html:
2016-11-30 12:08:35 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/bin/es.html:
2016-11-30 12:08:35 ERROR 404: NOT FOUND.
http://127.0.0.1:8000/static/api/bin/es_bash_completion.sh.html:
2016-11-30 12:08:35 ERROR 404: NOT FOUND.
```

**Comment by dn0** [comment]
@mbag After running ctl.sh collectstatic and ctl.sh compress --force I see only one 404 for robots.txt
