### ISSUE TITLE
Update `update_command` to re-use old SSL key/cert

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#104]
- move `ssl_key_file` and `ssl_cert_file` variable into core.settings, name them e.g. `UPDATE_KEY_FILE`, `UPDATE_CERT_FILE`
- check if key/cert file exists during each run (with key/cert=None) and pass them to the udpate script

**Comment by mbag** [comment]
@dn0 I added suggested variables to core.settings.  
The use case you mentioned, when remote is changed from EE to CE version, must be checked in the update script, since information about git repository is parsed and checked there. We can check if remote url starts with "github.com" and not export key/cert env variables.  
At this point if key/cert file was ever created and still exists we will be using them to call the update script.
