### ISSUE TITLE
Memory leak in erigonesd on node with network down

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#207]
On compute node: Cut connection from erigonesd to rabbitmq/redis and watch constant memory usage increasing.

**Comment by secult** [comment]
This issue happens when librabbitmq is used as a transport backend.
Recompilation of the pypi package doesn't help.
Recompilation from development source code doesn't help.

 When we switch to pyamqp, the leak is not happening. After some testing I will publish a fix, temporarily it's needed only to change the "amqp://" prefix of the transport backend to "pyamqp://" in the local_config.py and restart the worker.

**Comment by dn0** [comment]
Lets remove `librabbitmq` from requirements.txt and add `ctl.sh pip_uninstall librabbitmq` + *erigonesd restart* to our upcoming update.
