### ISSUE TITLE
Simplify registration and password reset

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#225]
Users are not aware that after opening a unique link (registration/password reset) they need to click on the button to confirm the password reset.

**Comment by secult** [comment]
I would suggest to use the default django password reset workflow

**Comment by ricco386** [comment]
We use two auth registration and password rest, where we send password via sms message. This have to stay build in.

**Comment by ricco386** [comment]
Current status:

Registratin steps:
* Click Sign in
* Fill the form and submit
* User see a message (email with verification link is send out)
* User click on email link
* User see a message (sms with password is send out)


Reset password steps:
* Click Forgotten password
* Fill the form and submit 
* User see a message (email with verification link is send out)
* User click on email link
* User see a message and click on confirm button
* User see a message (sms with password is send out)

**Comment by ricco386** [comment]
After long discussion with @secult we have identified few possible improvements (not sure if any will be implemented, but I wanted to make a note). Possible issue: generated passwords vs. user created passwords.

Registration asks for phone and email to be sure that whoever registered is a real person. However password reset does not need this, we already know that user is real person. Therefore email should be enough. Other possibility is that after click on unique one time link user can enter password by himself. Since we dont want to lower security for existing installations (and change backwards functionality behavior), there shall be setting Either send password via email, or via phone (leave as it is now).

Possible problem is that user dosnt have the phone anymore his administrator have to change his phone number in order to be able to reset the password.

Instead of sending password via sms, we will just issue one time token via sms and user can enter his password (either through registration or thought forgotten password), and immediately after login he have to enter this one time token.

**Comment by ricco386** [comment]
Created PR #234 Most of the changes are just a text changes and formated text into blocks. I have removed one step during the password reset (so the form is auto submitted).

Some issues discussed [above](https://github.com/erigones/esdc-ce/issues/225#issuecomment-321569755) has been created as a separate issue #235

**Comment by dn0** [comment]
Merged PR #234 
Issue continues with #235
