### ISSUE TITLE
Remove VMS_NET_NIC_TAGS -> switch to a real list of nic tags

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#227]
The list will based on NIC tags collected after #226 is implemented.
It can be cached in redis.

**Comment by YanChii** [comment]
When doing discovery on a node, please add to the nictag list also etherstubs. It is the preparation of support of networks on etherstubs. It will require new database field to identify type of the nictag (normal, overlay rule, etherstub).

**Comment by mbag** [comment]
@YanChii this should probably be in the issue #226, since code parsing output is there. But lets leave it here anyway.
The way nic tag discovery is currently implemented, it will collect anything that is the output of the `nictagadm list`, so by default etherstubs get parsed. However, overlays are not listed in the output of `nictagadm list` command. Do we need to parse `dladm show-overlays` or some other command to obtain overlay rule information?

Here is the partial output from es command, as currently implemented (some data omitted, but it is present, trust me :D ). If you prefer, we can change the name of the key from "NIC Tags" to something more general.
Any suggestions what should the name be?
```   
"NIC Tags": [
                        {
                            "link": "", 
                            "mac": "", 
                            "type": "normal", 
                            "name": "test1"
                        }, 
                        {
                            "link": "", 
                            "mac": "", 
                            "type": "normal", 
                            "name": "test2"
                        }, 
                        {
                            "link": null, 
                            "mac": null, 
                            "type": "etherstub", 
                            "name": "test3"
                        }
```

**Comment by mbag** [comment]
@YanChii my bad, after consulting with @dn0 it became clear that `nictagadm list` will show overlay rules as well. However, there is a problem with `nictagadm` code. It reads overlay rules from overlay file. If you create new overlay using `dladm create-overlay` it will not be shown.

Furthermore, the fact that file name is hard-coded has implications for our overlays, since we wil have to copy the file into `/var/run/smartdc/networking`. But this will be important later on.
