### ISSUE TITLE
Management does not recognize "stopped" status of half-installed BSD VM

### ISSUE THREAD

**Issue by ghost** [erigones/esdc-ce#314]
If I do "Force shutdown" of BSD VM amidst the installation, machine ends up unbootable (as expected) but management is still assuming that the machine is "stopping" even when vmadm already sees the machine as "stopped".

![image](https://user-images.githubusercontent.com/11230166/33245440-2f6de69e-d308-11e7-8cf2-e017ee2c975d.png)

Subsequent call to "vmadm start" causes the management to properly recognize status as "running".

**Comment by jurajlutter** [comment]
Workaround is to use "vmadm stop" from command line.

**Comment by dn0** [comment]
Hi @jurajlutter 

Which version of Danube Cloud is this?

I don't see a `Status of server changed` message in the task log. Can you please confirm that there is no such message from that time?

Usually when you start/stop/reboot a VM, Danube Cloud waits for an event from a sysevent thread (run under `erigonesd:fast`) and this event will change the status of the VM in DC's DB. It would be great if we could find out what happened to that event/task. In order to do that we can follow a trail from the compute node (`grep vm_status_event_cb /opt/erigones/var/log/fast.log`) up to the `mgmt.log` on mgmt01.local.

**Comment by DigitalOzUT** [comment]
Hello,
I have been working on this issue for about a month. I think I finally figured it out. Could you check and make sure the Date and Time is correct on the servers, and all of your VMs?

**Comment by YanChii** [comment]
The creator's account does not exist anymore. We will not get any feedback nor any new info.
Closing. If someone experiences this issue again, please reopen or create new issue.
