### ISSUE TITLE
No esdc-platform-upgrade file on v2.6.7 nodes.

### ISSUE THREAD

**Issue by DigitalOzUT** [erigones/esdc-ce#353]
Following the Updating Platform Image on Compute Nodes.
https://docs.danubecloud.org/user-guide/maintenance/update.html#updating-platform-image-on-compute-nodes 
There is no file named esdc-platform-upgrade located in the /opt/erigones/bin/ on any computer node running version 2.6.7

**Comment by dn0** [comment]
The `esdc-platform-upgrade` command was introduced in v3.0. You have to first update the Danube Cloud software in `/opt/erigones`. And since you are updating from 2.6.x, you have to perform a manual update: https://docs.danubecloud.org/user-guide/maintenance/update.html#updating-danube-cloud-software-manually (The procedure is the same as on the mgmt VM. The mgmt VM must be update first).
