### ISSUE TITLE
install on smartos

### ISSUE THREAD

**Issue by n1ete** [erigones/esdc-ce#443]
hey there, just stumbled upon your git and I like to try danube out...since I am running smartos already, can I just import all settings and just swap USB sticks?

lg

**Comment by YanChii** [comment]
Hi @lg,

We are happy you'd like to try Danube Cloud.
There are several ways how to convert plain SmartOS into the DC.
This article might give you an overview of what's needed:
https://danubecloud.com/danube-cloud-on-smartos/

From my point of view, the easiest way is very simmilar to what you've suggested - rewrite the USB stick with DC 1st compute node image (the one that has `hn` in the name), put the additional DC-related variables into the `/usbkey/config` and reboot. The dc/init script should take care of most things (like importing images and deploying management VMs).

Example of additional /usbkey/config settings:
```
# Danube Cloud settings                                                   
datacenter_name='yourDCname'                                                    
admin_email='your@mail.tld                                        
mgmt_admin_ip=10.100.10.100                                               
mon_admin_ip=10.100.10.101                                                
dns_admin_ip=10.100.10.102                                                
img_admin_ip=10.100.10.103                                                
cfgdb_admin_ip=10.100.10.104                                              
esdc_install_password='somepasswd'                                           
install_to_hdd=0
```
The IP addresses must belong to the network that you have already configured on the SmartOS box.

Then you will probably need to alter existing VMs to add network_uuid as described in the article above and run vm-harvest.

If you encouner some hiccup along the way, let us know and we will try help you with that.

Actually if you have multiple servers, there's one even easier way how to get DC running - fresh install first compute node on a clean server, migrate VMs to the new server using `esmigrate` script (included in the DC install) and do vm-harvest (adding network_uuid to existing VMs is still needed).

Let us know how it went for you.

Jan

**Comment by n1ete** [comment]
Thanks for the Answer i will try out Danube on the latest smartOS image first and will report back.
Btw. is there an comparison to the joyent sdc-triton solution?
How did you lower the resource requirements for danube cloud hn 
what monitoring system is used at tritons solution etc. i think it could be interesting for people who wanna try danube to have an overview of a decent comparison.
gretings

**Comment by YanChii** [comment]
We probably don't have a direct comparison of Danube Cloud (DC) to Triton SDC.
But roughly speaking, it's like this 
(if I'm wrong with something, please anybody correct me):

What has Danube Cloud that Triton does not:
- fully integrated/automated monitoring solution using Zabbix
- operator-delegated monitoring with multiple Zabbix servers
- fully integrated/automated backup (consistent incremental zfs remote backup implementation with support of qemu-agent)
- automated DNS management
- VM migrations across SmartOS hosts available in GUI
- live migration of KVM VMs
- automated overlay networking deployment
- multi-site deployment including overlay networking with IPSec to remote nodes
- VM disk continous replication (one-click instant VM restore in case of a SmartOS node failure)
- SmartOS disk-install support
- fiber channel and iSCSI disks support

What has Danube Cloud better than Triton:
- nicer GUI working well also in mobile browsers
- simpler, thinner management (one mgmt VM is enough for base functions, 4 other for full functionality - compared to a LOT of management VMs in Triton)
- the above means we don't need a dedicated headnode and you can operate your VM on a headnode (= first compute node)
- you can even migrate the mgmt VMs to other SmartOS nodes thus the headnode concept is only a virtual one

What has Danube Cloud the same as Triton:
- Web portal (but Triton GUI is a bit ugly and sometimes confusing)
- API
- RBAC access levels
- VM images with cloud-init
- VM metadata support
- VM snapshots
- integrated image server
- automated IP addressing and network management
- multitennant architecture with many virtual datacenters
- HA support
- possibility of creating public cloud 
- hybrid cloud (remote compute node in Danube Cloud implementation)
- Automated installation
- USB boot, PXE boot
- asynchronous architecture
- bulk imports
- automated upgrades
- support

What has Triton better than Danube Cloud:
- terraform support
- VM traits support - VM positioning according to specific requirements (e.g. high compute, SSD, large disk, etc)
- VM external firewall in GUI
- Kubernetes integration (we are working on it in DC)
- bhyve support (coming in DC)


Just a note: although you can install Danube Cloud on any plain SmartOS, since DC `v3.0.0`, we are modyfying also the underlying SmartOS itself to have some additional features. Therefore it's always better to have the DC-branded SmartOS (either do a clean install of DC or use `esdc-platform-upgrade` after you install a DC on a plain SmartOS). By doing a clean install, you will avoid some complications that have not been tested that much.

Jan

**Comment by n1ete** [comment]
hey there again,
thanks for the explanation i would add an comparison to the docs somewhere.
i the meantime i went successful into installing danube cloud...i decided to export my vms and went with an fresh install. i didnt configure much, neither had time to inspect everything or import my vms back yet.

i have a suggestion to add to the "factory-reset" section in the docss though.

you suggest in the docs to do a factory reset with 'destroy_zpools=true' and reboot or manual formating.

i think if you do a 'destroy_zpools=true' it will destroy all zpools, not only the zones zfs-pool.

this could have destroyed my zfs 'storagepool' aswell after reboot. if thats true youi need to address this in the docs right, but maybe my assumption is wrong here?

besides this little missing note, the documentation is very well written and my experience with esdc and the support here is superb! thanks! will preparing a public review the next months, because i think this needs more attention, i will publish the link here ;) 

i hope this project keeps maintained a long time since i already have plans to roll this out on some of my customers.

as soon as i find time, more questions will arise in using esdc for sure...

greetings and a big shoutout to the Erigones/Danube Team

**Comment by YanChii** [comment]
Hi @n1ete 

Thanks for the docs suggestion. I've made a [docs PR](https://github.com/erigones/esdc-docs/commit/228473ec3701ca917905a3cc2188f386b481af94) adding a warning.

Your questions are welcome. Danube Cloud can do a lot and not everything might be apparent immediately.

We are very happy that you'd like to write something about Danube. I must admit that letting people know about us is currently probably our biggest weakness. 

Thank you.

Jan

**Comment by StevenWilliams** [comment]
When is bhyve support coming? What version of Smart OS is Danube based on?

**Comment by YanChii** [comment]
Hi @StevenWilliams 

For the current SmartOS version see [release notes](url)

The current platform today is 20190422T104439Z as this is the last version with grub support. The newest version will have most current platform with BSD loader and UEFI (#450 ).

The bhyve support is quite high on our wishlist. I can't tell you exact date but we're working on it. The integration is not trivial as the VNC support is present only with UEFI VM bootcode what also requires different images. And also many other changes through the code.

Jan
